# Generated by Django 5.2.6 on 2025-10-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta Adresi')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('accept_terms', models.BooleanField(verbose_name='Kişisel verilerin işlenmesini kabul etti')),
                ('subscribe_newsletter', models.BooleanField(default=False, verbose_name='Kampanya ve duyurular hakkında bilgilendirilmek istiyor')),
                ('is_sent', models.BooleanField(default=False, editable=False, verbose_name='E-posta Gönderildi mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'İletişim Formu Mesajı',
                'verbose_name_plural': 'İletişim Formu Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='Örn: smtp.gmail.com', max_length=255)),
                ('port', models.PositiveIntegerField(default=587, help_text='Örn: 587 (TLS için)')),
                ('user', models.EmailField(help_text='Gönderici e-posta adresi', max_length=254)),
                ('password', models.TextField(help_text='E-posta şifresi (Uygulama Şifresi)')),
                ('use_tls', models.BooleanField(default=True, help_text='TLS kullanılsın mı?')),
                ('recipient_email', models.EmailField(help_text='İletişim formu mesajlarının gönderileceği e-posta adresi', max_length=254, verbose_name='Alıcı E-posta Adresi')),
            ],
            options={
                'verbose_name': 'E-posta Gönderim Ayarı',
                'verbose_name_plural': 'E-posta Gönderim Ayarları',
            },
        ),
    ]
