# Generated by Django 5.2.6 on 2025-10-07 17:39

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_alter_item_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
                ('site_title', models.CharField(max_length=255)),
                ('site_title_tr', models.CharField(max_length=255, null=True)),
                ('site_title_en', models.CharField(max_length=255, null=True)),
                ('site_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('site_description_tr', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('site_description_en', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='site_settings.sitesettings')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_tr', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_tr', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='site/header/')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='site_settings.sitesettings')),
            ],
        ),
        migrations.CreateModel(
            name='GenericSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_tr', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('title_tr', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_tr', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('button_text_left', models.CharField(blank=True, max_length=255, null=True)),
                ('button_text_left_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('button_text_left_en', models.CharField(blank=True, max_length=255, null=True)),
                ('button_url_left', models.URLField(blank=True, null=True)),
                ('button_text_right', models.CharField(blank=True, max_length=255, null=True)),
                ('button_text_right_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('button_text_right_en', models.CharField(blank=True, max_length=255, null=True)),
                ('button_url_right', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='site/sections/')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='site_settings.sitesettings')),
            ],
        ),
        migrations.CreateModel(
            name='FooterPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_tr', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_tr', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_policies', to='site_settings.sitesettings')),
            ],
        ),
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/footer/')),
                ('footer_text', models.CharField(default='kitti.com.tr © 2025 - Tüm hakları saklıdır.', max_length=255)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='footer_info', to='site_settings.sitesettings')),
            ],
        ),
        migrations.CreateModel(
            name='FavoritesOfSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_tr', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('button_text', models.CharField(max_length=255)),
                ('button_text_tr', models.CharField(max_length=255, null=True)),
                ('button_text_en', models.CharField(max_length=255, null=True)),
                ('button_url', models.URLField()),
                ('product_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.item')),
                ('product_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.item')),
                ('product_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.item')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_section', to='site_settings.sitesettings')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='site_settings.sitesettings')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsKitty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='site/sections/')),
                ('title', models.CharField(max_length=255)),
                ('title_tr', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_tr', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('button_text', models.CharField(max_length=255)),
                ('button_text_tr', models.CharField(max_length=255, null=True)),
                ('button_text_en', models.CharField(max_length=255, null=True)),
                ('button_url', models.URLField()),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whats_kitty', to='site_settings.sitesettings')),
            ],
        ),
    ]
