# Generated by Django 5.2.6 on 2025-10-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerinfo',
            name='footer_text_en',
            field=models.CharField(default='kitti.com.tr © 2025 - Tüm hakları saklıdır.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='footer_text_tr',
            field=models.CharField(default='kitti.com.tr © 2025 - Tüm hakları saklıdır.', max_length=255, null=True),
        ),
    ]
