# Generated by Django 4.2.25 on 2025-11-10 10:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_item_category_type'),
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_tr', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_tr', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tel', models.CharField(max_length=255)),
                ('tel_wp', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GenericSectionContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_tr', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_tr', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'İletişim Sayfası Ayarı',
                'verbose_name_plural': 'İletişim Sayfası Ayarları',
            },
        ),
        migrations.CreateModel(
            name='GenericSectionOurStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('big_story', 'Big Story'), ('all_over', 'All Over'), ('power_of_a_group', 'Power Of a Group'), ('what_do_we_produce', 'What Do We Produce'), ('best_selling_accessories', 'Best Selling Accessories'), ('health_and_quality', 'Health and Quality'), ('safe_facilities', 'Safe Facilities'), ('harmless_materials', 'Harmless Materials'), ('growing_safely', 'Growing Safely'), ('kitti_products', 'Kitti Products')], default='generic_our_story', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('name_tr', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('title_tr', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_tr', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('subimage', models.FileField(blank=True, null=True, upload_to='site/sections/our_story')),
                ('subimage_tr', models.FileField(blank=True, null=True, upload_to='site/sections/our_story')),
                ('subimage_en', models.FileField(blank=True, null=True, upload_to='site/sections/our_story')),
                ('mobile_image', models.FileField(blank=True, null=True, upload_to='site/sections/our_story')),
                ('image', models.FileField(blank=True, null=True, upload_to='site/sections/our_story')),
                ('button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_text_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('button_text_en', models.CharField(blank=True, max_length=255, null=True)),
                ('button_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Hikayemiz Sayfası Bölümü',
                'verbose_name_plural': 'Hikayemiz Sayfası Bölümleri',
            },
        ),
        migrations.CreateModel(
            name='GenericSectionWholesale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_tr', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_tr', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('info_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('info_text_tr', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('info_text_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='site/sections/wholasale')),
                ('button_top_title', models.CharField(blank=True, max_length=255, null=True)),
                ('button_top_title_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('button_top_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('button_top_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_top_text_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('button_top_text_en', models.CharField(blank=True, max_length=255, null=True)),
                ('button_top_url', models.CharField(blank=True, max_length=500, null=True)),
                ('button_bottom_title', models.CharField(blank=True, max_length=255, null=True)),
                ('button_bottom_title_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('button_bottom_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('button_bottom_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_bottom_text_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('button_bottom_text_en', models.CharField(blank=True, max_length=255, null=True)),
                ('button_bottom_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Toptan Satış Sayfası Ayarı',
                'verbose_name_plural': 'Toptan Satış Sayfası Ayarları',
            },
        ),
        migrations.RemoveField(
            model_name='whatskitty',
            name='site',
        ),
        migrations.AlterModelOptions(
            name='footerinfo',
            options={'verbose_name': 'Footer Bilgisi', 'verbose_name_plural': 'Footer Bilgi Ayarları'},
        ),
        migrations.AlterModelOptions(
            name='footerpolicy',
            options={'verbose_name': 'Politika', 'verbose_name_plural': 'Politika Ayarları'},
        ),
        migrations.AlterModelOptions(
            name='genericsection',
            options={'verbose_name': 'Ana Sayfa Bölümü', 'verbose_name_plural': 'Ana Sayfa Bölüm Ayarları'},
        ),
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Ana Sayfa Header', 'verbose_name_plural': 'Ana Sayfa Header Ayarları'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['id'], 'verbose_name': 'Menü Elemanı', 'verbose_name_plural': 'Menü Elemanları'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Genel Site Ayarı', 'verbose_name_plural': 'Genel Site Ayarları'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Sosyal Medya Linki', 'verbose_name_plural': 'Sosyal Medya Linkleri'},
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='footer_text_en',
            field=models.CharField(default='kitti.com.tr © 2025 - Tüm hakları saklıdır.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='footer_text_tr',
            field=models.CharField(default='kitti.com.tr © 2025 - Tüm hakları saklıdır.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='social_text',
            field=models.CharField(default='Yenilikleri Kaçırmayın;', max_length=255),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='social_text_en',
            field=models.CharField(default='Yenilikleri Kaçırmayın;', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='social_text_tr',
            field=models.CharField(default='Yenilikleri Kaçırmayın;', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsection',
            name='mobile_image',
            field=models.FileField(blank=True, null=True, upload_to='site/sections/'),
        ),
        migrations.AddField(
            model_name='genericsection',
            name='product_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.item'),
        ),
        migrations.AddField(
            model_name='genericsection',
            name='product_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.item'),
        ),
        migrations.AddField(
            model_name='genericsection',
            name='product_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.item'),
        ),
        migrations.AddField(
            model_name='genericsection',
            name='type',
            field=models.CharField(choices=[('whats_kitty', "What's Kitty"), ('favorites_of_season', 'Favorites of Season'), ('who_are_we', 'Who Are We'), ('from_the_workshop', 'From the Workshop'), ('its_story', 'Its Story'), ('production_capacity', 'Production Capacity'), ('generic', 'Generic Section')], default='generic', max_length=50),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='text_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.FileField(blank=True, help_text='Site ikonu (favicon). Genellikle .ico, .png veya .svg formatında olur.', null=True, upload_to='site/favicon/'),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='site/footer/'),
        ),
        migrations.AlterField(
            model_name='genericsection',
            name='button_url_left',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='genericsection',
            name='button_url_right',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='genericsection',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='site/sections/'),
        ),
        migrations.AlterField(
            model_name='header',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='site/header/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='site/logo/'),
        ),
        migrations.DeleteModel(
            name='FavoritesOfSeason',
        ),
        migrations.DeleteModel(
            name='WhatsKitty',
        ),
        migrations.AddField(
            model_name='genericsectionwholesale',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_wholasale', to='site_settings.sitesettings'),
        ),
        migrations.AddField(
            model_name='genericsectionourstory',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_our_story', to='site_settings.sitesettings'),
        ),
        migrations.AddField(
            model_name='genericsectioncontact',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_contact', to='site_settings.sitesettings'),
        ),
        migrations.AddField(
            model_name='contactmails',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_mails', to='site_settings.genericsectioncontact'),
        ),
        migrations.AddField(
            model_name='contactaddresses',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_address', to='site_settings.genericsectioncontact'),
        ),
    ]
