# Generated by Django 4.2.25 on 2025-11-10 13:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_contactaddresses_contactmails_genericsectioncontact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('question_tr', models.CharField(max_length=500, null=True)),
                ('question_en', models.CharField(max_length=500, null=True)),
                ('answer', ckeditor.fields.RichTextField()),
                ('answer_tr', ckeditor.fields.RichTextField(null=True)),
                ('answer_en', ckeditor.fields.RichTextField(null=True)),
                ('order', models.IntegerField(default=0, help_text='Sıralama için kullanılır')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='site_settings.sitesettings')),
            ],
            options={
                'verbose_name': 'FAQ Öğesi',
                'verbose_name_plural': 'FAQ Öğeleri',
                'ordering': ['order', 'id'],
            },
        ),
    ]
