# Generated by Django 5.2.6 on 2025-10-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_footerinfo_footer_text_en_footerinfo_footer_text_tr'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='text_tr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
