# Generated by Django 4.2.25 on 2025-11-11 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_alter_socialmedia_url_faqitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', '/'), ('products', '/products'), ('our-story', '/our-story'), ('contact', '/contact'), ('toptan-portal', '/toptan-portal'), ('aydinlatma-metni', '/aydinlatma-metni'), ('cerez-politikasi', '/cerez-politikasi'), ('ileti-onay-metni', '/ileti-onay-metni')], max_length=50, unique=True)),
                ('meta_title_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title (TR)')),
                ('meta_title_tr_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title (TR)')),
                ('meta_title_tr_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title (TR)')),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title (EN)')),
                ('meta_title_en_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title (EN)')),
                ('meta_title_en_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title (EN)')),
                ('meta_description_tr', models.TextField(blank=True, null=True, verbose_name='Meta Description (TR)')),
                ('meta_description_tr_tr', models.TextField(blank=True, null=True, verbose_name='Meta Description (TR)')),
                ('meta_description_tr_en', models.TextField(blank=True, null=True, verbose_name='Meta Description (TR)')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='Meta Description (EN)')),
                ('meta_description_en_tr', models.TextField(blank=True, null=True, verbose_name='Meta Description (EN)')),
                ('meta_description_en_en', models.TextField(blank=True, null=True, verbose_name='Meta Description (EN)')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_metas', to='site_settings.sitesettings')),
            ],
            options={
                'verbose_name': 'Sayfa Meta Bilgisi',
                'verbose_name_plural': 'Sayfa Meta Bilgileri',
                'ordering': ['page'],
            },
        ),
    ]
