# Generated by Django 5.2.6 on 2025-10-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_menuitem_text_en_menuitem_text_tr'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritesofseason',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site/sections/'),
        ),
    ]
