# Generated by Django 5.2.6 on 2025-10-07 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_item_category_type'),
        ('site_settings', '0004_favoritesofseason_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatskitty',
            name='site',
        ),
        migrations.AddField(
            model_name='genericsection',
            name='product_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.item'),
        ),
        migrations.AddField(
            model_name='genericsection',
            name='product_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.item'),
        ),
        migrations.AddField(
            model_name='genericsection',
            name='product_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.item'),
        ),
        migrations.AddField(
            model_name='genericsection',
            name='type',
            field=models.CharField(choices=[('whats_kitty', "What's Kitty"), ('favorites_of_season', 'Favorites of Season'), ('generic', 'Generic Section')], default='generic', max_length=50),
        ),
        migrations.DeleteModel(
            name='FavoritesOfSeason',
        ),
        migrations.DeleteModel(
            name='WhatsKitty',
        ),
    ]
