# Generated by Django 4.2.25 on 2025-11-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_pagemeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemeta',
            name='page',
            field=models.CharField(choices=[('home', '/'), ('products', '/products'), ('our-story', '/our-story'), ('contact', '/contact'), ('toptan-portal', '/toptan-portal'), ('aydinlatma-metni', '/aydinlatma-metni'), ('cerez-politikasi', '/cerez-politikasi'), ('ileti-onay-metni', '/ileti-onay-metni')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='pagemeta',
            unique_together={('site', 'page')},
        ),
    ]
