# Generated by Django 4.2.25 on 2025-11-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_alter_pagemeta_page_alter_pagemeta_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagemeta',
            name='meta_description_en_en',
        ),
        migrations.RemoveField(
            model_name='pagemeta',
            name='meta_description_en_tr',
        ),
        migrations.RemoveField(
            model_name='pagemeta',
            name='meta_description_tr_en',
        ),
        migrations.RemoveField(
            model_name='pagemeta',
            name='meta_description_tr_tr',
        ),
        migrations.RemoveField(
            model_name='pagemeta',
            name='meta_title_en_en',
        ),
        migrations.RemoveField(
            model_name='pagemeta',
            name='meta_title_en_tr',
        ),
        migrations.RemoveField(
            model_name='pagemeta',
            name='meta_title_tr_en',
        ),
        migrations.RemoveField(
            model_name='pagemeta',
            name='meta_title_tr_tr',
        ),
    ]
