# Generated by Django 5.2.6 on 2025-10-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_remove_whatskitty_site_genericsection_product_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericsection',
            name='button_url_left',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genericsection',
            name='button_url_right',
            field=models.CharField(blank=True, null=True),
        ),
    ]
