# Generated by Django 5.2.6 on 2025-10-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_alter_genericsection_button_url_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericsection',
            name='type',
            field=models.CharField(choices=[('whats_kitty', "What's Kitty"), ('favorites_of_season', 'Favorites of Season'), ('who_are_we', 'Who Are We'), ('production_capacity', 'Production Capacity'), ('its_story', 'Its Story'), ('generic', 'Generic Section')], default='generic', max_length=50),
        ),
    ]
