# Generated by Django 5.2.6 on 2025-10-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_alter_genericsection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerinfo',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='site/footer/'),
        ),
        migrations.AlterField(
            model_name='genericsection',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='site/sections/'),
        ),
        migrations.AlterField(
            model_name='genericsection',
            name='type',
            field=models.CharField(choices=[('whats_kitty', "What's Kitty"), ('favorites_of_season', 'Favorites of Season'), ('who_are_we', 'Who Are We'), ('from_the_workshop', 'From the Workshop'), ('its_story', 'Its Story'), ('production_capacity', 'Production Capacity'), ('generic', 'Generic Section')], default='generic', max_length=50),
        ),
        migrations.AlterField(
            model_name='header',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='site/header/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='site/logo/'),
        ),
    ]
