# Generated by Django 5.2.6 on 2025-10-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_alter_footerinfo_logo_alter_genericsection_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericsection',
            name='mobile_image',
            field=models.FileField(blank=True, null=True, upload_to='site/sections/'),
        ),
    ]
