# Generated by Django 5.2.6 on 2025-10-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_genericsection_mobile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericsection',
            name='page',
            field=models.CharField(choices=[('home_page', 'Home Page'), ('our_story', 'Our Story'), ('contact', 'Contact'), ('wholesale_portal', 'Wholesale Portal')], default='home_page', max_length=50),
        ),
    ]
