# Generated by Django 5.2.6 on 2025-10-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0010_genericsection_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericsection',
            name='page',
        ),
    ]
