# Generated by Django 5.2.6 on 2025-10-09 07:26

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0011_remove_genericsection_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericSectionOurStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('big_story', 'Big Story'), ('all_over', 'All Over'), ('power_of_a_group', 'Power Of a Group'), ('what_do_we_produce', 'What Do We Produce'), ('best_selling_accessories', 'Best Selling Accessories'), ('health_and_quality', 'Health and Quality'), ('safe_facilities', 'Safe Facilities'), ('Harmless Materials', 'Harmless Materials'), ('growing_safely', 'Growing Safely'), ('kitti_products', 'Kitti Products')], default='generic_our_story', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('subimage', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_image', models.FileField(blank=True, null=True, upload_to='site/sections/our_story')),
                ('image', models.FileField(blank=True, null=True, upload_to='site/sections/our_story')),
                ('button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_url', models.CharField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_our_story', to='site_settings.sitesettings')),
            ],
        ),
    ]
