# Generated by Django 5.2.6 on 2025-10-09 07:31

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0012_genericsectionourstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericSectionContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_contact', to='site_settings.sitesettings')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=255)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_mails', to='site_settings.genericsectioncontact')),
            ],
        ),
        migrations.CreateModel(
            name='ContactAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tel', models.CharField(max_length=255)),
                ('tel_wp', models.CharField(max_length=255)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_address', to='site_settings.genericsectioncontact')),
            ],
        ),
    ]
