# Generated by Django 5.2.6 on 2025-10-09 07:36

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0013_genericsectioncontact_contactmails_contactaddresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericSectionWholesale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('info_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='site/sections/wholasale')),
                ('button_top_title', models.CharField(blank=True, max_length=255, null=True)),
                ('button_top_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_top_url', models.CharField(blank=True, null=True)),
                ('button_bottom_title', models.CharField(blank=True, max_length=255, null=True)),
                ('button_bottom_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_bottom_url', models.CharField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_wholasale', to='site_settings.sitesettings')),
            ],
        ),
    ]
