# Generated by Django 5.2.6 on 2025-10-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0014_genericsectionwholesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerpolicy',
            name='social_text',
            field=models.CharField(default='Yenilikleri kaçırmayın;', max_length=255),
            preserve_default=False,
        ),
    ]
