# Generated by Django 5.2.6 on 2025-10-09 07:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0015_footerpolicy_social_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactaddresses',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactaddresses',
            name='description_tr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactaddresses',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactaddresses',
            name='title_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footerpolicy',
            name='social_text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footerpolicy',
            name='social_text_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsectioncontact',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genericsectioncontact',
            name='description_tr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genericsectioncontact',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsectioncontact',
            name='title_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionourstory',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionourstory',
            name='button_text_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionourstory',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionourstory',
            name='description_tr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionourstory',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionourstory',
            name='name_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionourstory',
            name='subimage_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionourstory',
            name='subimage_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionourstory',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionourstory',
            name='subtitle_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionourstory',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionourstory',
            name='title_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionwholesale',
            name='button_bottom_text_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionwholesale',
            name='button_bottom_text_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionwholesale',
            name='button_bottom_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionwholesale',
            name='button_bottom_title_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionwholesale',
            name='button_top_text_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionwholesale',
            name='button_top_text_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionwholesale',
            name='button_top_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionwholesale',
            name='button_top_title_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionwholesale',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionwholesale',
            name='description_tr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionwholesale',
            name='info_text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionwholesale',
            name='info_text_tr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionwholesale',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericsectionwholesale',
            name='title_tr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
