# Generated by Django 5.2.6 on 2025-10-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0016_contactaddresses_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerpolicy',
            name='social_text',
        ),
        migrations.RemoveField(
            model_name='footerpolicy',
            name='social_text_en',
        ),
        migrations.RemoveField(
            model_name='footerpolicy',
            name='social_text_tr',
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='social_text',
            field=models.CharField(default='Yenilikleri Kaçırmayın;', max_length=255),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='social_text_en',
            field=models.CharField(default='Yenilikleri Kaçırmayın;', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='social_text_tr',
            field=models.CharField(default='Yenilikleri Kaçırmayın;', max_length=255, null=True),
        ),
    ]
