# Generated by Django 5.2.6 on 2025-10-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0017_remove_footerpolicy_social_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerinfo',
            options={'verbose_name': 'Footer Bilgisi', 'verbose_name_plural': 'Footer Bilgi Ayarları'},
        ),
        migrations.AlterModelOptions(
            name='footerpolicy',
            options={'verbose_name': 'Politika', 'verbose_name_plural': 'Politika Ayarları'},
        ),
        migrations.AlterModelOptions(
            name='genericsection',
            options={'verbose_name': 'Ana Sayfa Bölümü', 'verbose_name_plural': 'Ana Sayfa Bölüm Ayarları'},
        ),
        migrations.AlterModelOptions(
            name='genericsectioncontact',
            options={'verbose_name': 'İletişim Sayfası Ayarı', 'verbose_name_plural': 'İletişim Sayfası Ayarları'},
        ),
        migrations.AlterModelOptions(
            name='genericsectionourstory',
            options={'verbose_name': 'Hikayemiz Sayfası Bölümü', 'verbose_name_plural': 'Hikayemiz Sayfası Bölümleri'},
        ),
        migrations.AlterModelOptions(
            name='genericsectionwholesale',
            options={'verbose_name': 'Toptan Satış Sayfası Ayarı', 'verbose_name_plural': 'Toptan Satış Sayfası Ayarları'},
        ),
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Ana Sayfa Header', 'verbose_name_plural': 'Ana Sayfa Header Ayarları'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Genel Site Ayarı', 'verbose_name_plural': 'Genel Site Ayarları'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Sosyal Medya Linki', 'verbose_name_plural': 'Sosyal Medya Linkleri'},
        ),
        migrations.AlterField(
            model_name='genericsectionourstory',
            name='type',
            field=models.CharField(choices=[('big_story', 'Big Story'), ('all_over', 'All Over'), ('power_of_a_group', 'Power Of a Group'), ('what_do_we_produce', 'What Do We Produce'), ('best_selling_accessories', 'Best Selling Accessories'), ('health_and_quality', 'Health and Quality'), ('safe_facilities', 'Safe Facilities'), ('harmless_materials', 'Harmless Materials'), ('growing_safely', 'Growing Safely'), ('kitti_products', 'Kitti Products')], default='generic_our_story', max_length=50),
        ),
    ]
