# Generated by Django 5.2.6 on 2025-10-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0018_alter_footerinfo_options_alter_footerpolicy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericsectionourstory',
            name='subimage',
            field=models.FileField(blank=True, null=True, upload_to='site/sections/our_story'),
        ),
        migrations.AlterField(
            model_name='genericsectionourstory',
            name='subimage_en',
            field=models.FileField(blank=True, null=True, upload_to='site/sections/our_story'),
        ),
        migrations.AlterField(
            model_name='genericsectionourstory',
            name='subimage_tr',
            field=models.FileField(blank=True, null=True, upload_to='site/sections/our_story'),
        ),
    ]
