# Generated by Django 5.2.6 on 2025-10-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0019_alter_genericsectionourstory_subimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.FileField(blank=True, help_text='Site ikonu (favicon). Genellikle .ico, .png veya .svg formatında olur.', null=True, upload_to='site/favicon/'),
        ),
    ]
