# Generated by Django 5.2.6 on 2025-09-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_category_remove_product_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
