# Generated by Django 5.2.6 on 2025-09-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image_en',
            field=models.ImageField(null=True, upload_to='sliders/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='image_tr',
            field=models.ImageField(null=True, upload_to='sliders/'),
        ),
    ]
