# Generated by Django 5.2.6 on 2025-10-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_slider_image_en_slider_image_tr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category_type',
            field=models.CharField(blank=True, choices=[('type1', 'Card View'), ('type2', 'List View'), ('type3', 'Slider Card View'), ('type4', 'Gallery Horizantal Card View'), ('type5', 'Gallery Vertical Card View')], help_text='Only for categories', max_length=50, null=True),
        ),
    ]
