# Generated by Django 4.2.25 on 2025-11-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_item_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image_tr',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/'),
        ),
    ]
